version: 2

main: &main
    machine: true
    steps:
      - checkout
      - run:
          command: docker pull dorowu/ubuntu-desktop-lxde-vnc:trusty
      - run:
          name: Install system packages
          command: |
            sudo apt-get update
            sudo apt-get install libpulse-dev
            sudo apt-get install libegl1-mesa
      - run:
          command: ./.circleci/install.sh
      - run:
          command: ./.circleci/test-pyqt5.sh
      - run:
          command: ./.circleci/test-pyside2.sh
      - run:
          command: ./.circleci/test-pyqt4.sh
      - run:
          command: ./.circleci/test-pyside.sh
      - run:
          command: ./.circleci/coverage.sh

jobs:
  python2.7:
    <<: *main
    environment:
      - PYTHON_VERSION: "2.7"
      - USE_CONDA: "Yes"

  python3.5:
    <<: *main
    environment:
      - PYTHON_VERSION: "3.5"
      - USE_CONDA: "Yes"

  python3.6:
    <<: *main
    environment:
      - PYTHON_VERSION: "3.6"
      - USE_CONDA: "Yes"

  python3.7:
    <<: *main
    environment:
      - PYTHON_VERSION: "3.7"
      - USE_CONDA: "Yes"

  python3.8:
    <<: *main
    environment:
      - PYTHON_VERSION: "3.8"
      - USE_CONDA: "Yes"

  python2.7-pip:
    <<: *main
    environment:
      - PYTHON_VERSION: "2.7"
      - USE_CONDA: "No"

  python3.6-pip:
    <<: *main
    environment:
      - PYTHON_VERSION: "3.6"
      - USE_CONDA: "No"

  python3.7-pip:
    <<: *main
    environment:
      - PYTHON_VERSION: "3.7"
      - USE_CONDA: "No"

  python3.8-pip:
    <<: *main
    environment:
      - PYTHON_VERSION: "3.8"
      - USE_CONDA: "No"

workflows:
  version: 2
  build_and_test:
    jobs:
      - python2.7
      - python3.5
      - python3.6
      - python3.7
      - python3.8
      - python2.7-pip
      - python3.6-pip
      - python3.7-pip
      - python3.8-pip
